CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md
- Code of conduct
- Security 
- Contributing
=> Community Standards Files

Jenkinsfile
Add jenkinsfile to automate ui build
=> CAT-36 Automate ui build with jenkinsfile

package-lock.json, package.json, src/App.css, src/App.tsx, src/api/services/User.ts, src/auth/AuthContext.tsx, src/auth/KeycloakLogin.tsx, src/auth/ProtectedRoute.tsx, src/auth/index.ts, src/components/Header.tsx, src/components/Table.tsx, src/components/index.ts, src/pages/Home.tsx, src/pages/Profile.tsx, src/pages/Users.tsx, src/pages/index.ts, types.d.ts
- Introduce react-table library
- Support /users endpoint
- Create a view to display the retrieved information
- Various structural modifications
`NOTE! Review and merge after #8 `
=> [CAT-44] List of available users

package-lock.json, package.json, src/App.tsx, src/api/services/User.ts, src/auth/AuthContext.tsx, src/components/Header.tsx, src/pages/Profile.tsx, types.d.ts
This pull request integrates React Query for improved API data fetching, caching, and synchronization with the server. It simplifies API data management, enhances performance, and provides features like caching, loading states, and error handling.
=> [CAT-43] Integrate react-query

README.md, src/api/client.ts, src/config.json, src/config.tsx, types.d.ts
- Introduce a configuration file in JSON format
=> [CAT-45] Introduce basic configuration file

src/api/services/User.ts, src/components/Table.tsx, src/pages/Home.tsx, types.d.ts
- Fixed faulty pagination on the generic table component
- Fix typo on query params passed to requests on cat-api
=> [CAT-51] Fix bug on Table component pagination

src/api/services/User.ts, src/auth/AuthContext.tsx, src/auth/KeycloakLogin.tsx, src/auth/ProtectedRoute.tsx, src/components/Header.tsx, src/components/Table.tsx, src/pages/Home.tsx, src/pages/Profile.tsx, types.d.ts
- Issue a request to /users/register at user login
- Enable user requests only if token exists
=> [CAT-48] Register user at login

package-lock.json, package.json, src/App.tsx, src/api/index.ts, src/api/services/Validation.ts, src/pages/Profile.tsx, src/pages/Validations.tsx, src/pages/index.ts, types.d.ts
- Initial support of /validations endpoint
- Add form page for validation request
=> [CAT-53] Introduce validations

package-lock.json, package.json, src/api/index.ts, src/api/services/Actor.ts, src/api/services/Organisation.ts, src/pages/Validations.tsx, types.d.ts
- Retrieve and populate the form fields appropriately
- Introduce autocompletion for organisation name select
=> [CAT-58] Add autocompletion on validation request form

package-lock.json, src/App.css, src/App.tsx, src/api/services/Validation.ts, src/pages/Profile.tsx, src/pages/Validations.tsx, src/pages/index.ts, types.d.ts
-  Create a page to list all validations
-   if admin the user should be able to operate (view, edit) upon a view
=> [CAT-64] List of validations view

src/App.css, src/App.tsx, src/auth/KeycloakLogout.tsx, src/auth/index.ts, src/components/Header.tsx, src/pages/Profile.tsx, src/pages/Users.tsx, src/pages/Validations.tsx
=> CAT-67 Add view headers. Add Logout button. Cleanup routing

src/App.css, src/pages/Profile.tsx
=> CAT-71 Fix Profile Layout. Add Personal Details section

src/App.tsx, src/api/services/Validation.ts, src/components/Table.tsx, src/pages/Validations.tsx, src/pages/index.ts, types.d.ts
- Added a page to display detailed info about a validation
=> [CAT-65] Add validation Detailed view

src/App.tsx, src/auth/KeycloakLogout.tsx, src/components/Header.tsx, src/pages/ProfileUpdate.tsx, src/pages/index.ts
=> CAT-72 Update profile details

src/pages/Validations.tsx
- Fix some typos and redirection path
=> Fix typos on validations page

src/pages/Validations.tsx
=> Update validation layout

src/pages/Validations.tsx
Display user information on validation request page:
- user name
- user surname
- user email
=> [CAT-78] Display user information on validation request page

src/api/services/Validation.ts, src/pages/Validations.tsx
The user is now redirected to the list of validations after a successful validation request
=> [CAT-79] Fix redirection upon a successful validation request

src/pages/Validations.tsx, types.d.ts
Display user information on validation details page:
- user name
- user surname
- user email
- actor name
=> [CAT-80] Display more user and actor information on validation details

src/components/Footer.tsx, src/pages/Profile.tsx, src/pages/Validations.tsx
=> CAT-81 Minor UI fixes on validations, profile and footer

src/pages/Validations.tsx
Fix visibility of validation request admin buttons
=> CAT-81 Fix admin buttons in validation

src/App.css, src/components/Footer.tsx, src/pages/Profile.tsx
Add version & build information in a subtle way at the lower section of the footer.
Extras:
=> CAT-85 Add version and build info

src/components/Alert.js, src/components/index.ts, src/pages/Validations.tsx, src/pages/index.ts, types.d.ts
- Appropriate Alert should be displayed containing an informative message
- The validation status is described by a custom type to restrict its values and prevent typos during UI development
=> [CAT-62][CAT-73] Add Alert messages and Validation enumeration

src/api/services/User.ts, src/auth/KeycloakLogin.tsx, src/types/common.ts
- Removes redundant request to user registration endpoint if user is already registered
- Changes useQuery to useMutation for registration query
=> [CAT-118] Check if user is already registered when trying to register

src/App.tsx, src/api/services/Template.ts, src/api/services/Validation.ts, src/components/EvidenceURLS.tsx, src/components/Header.tsx, src/components/assessment/AssessmentInfo.tsx, src/components/tests/TestBinary.tsx, src/pages/AssessmentEdit.tsx, src/pages/Validations.tsx, src/types/assessment.ts
CAT-100 UI implement component to add list of evidence urls
Add a component to visualise BinaryTests and a sub component to be able to add evidence url
=> CAT-99 Implement Binary Test Component

src/api/services/User.ts, src/auth/KeycloakLogin.tsx
- Fix bug with registered state on context update
=> Fix missing registered context state

src/components/assessment/AssessmentInfo.tsx, src/pages/AssessmentEdit.tsx, src/types/assessment.ts
Add missing subject fields in Assessment Info Header
Add published field 
Connect state and change of state for name, subject and published fields through Parent and child components
=> CAT-150 Add subject and published fields in Assessment Info header

src/pages/ProfileUpdate.tsx
Add type=button to cancel to avoid the Form submission canceled because form not connected warning
=> CAT-154 Fix Profile Update Form not connected warning

src/App.css, src/components/EvidenceURLS.tsx, src/components/assessment/AssessmentInfo.tsx, src/components/tests/TestBinary.tsx, src/pages/AssessmentEdit.tsx, src/pages/Validations.tsx, src/types/assessment.ts
CAT-102 Display dynamic list of tests for each criterion/metric in assessment form
Generate dynamic list of Principles and Criteria in Assessment Form
For each criterion generate dynamically the list of tests
Update assessment state from test components
=> CAT-101 Display dynamically principles, criteria and metrics in the assessment form  

src/pages/Profile.tsx, src/pages/ProfileUpdate.tsx, src/types/profile.ts
- Add ORCID on profile view
- Add form field to add ORCID id on update profile data view
=> [CAT-138] Add ORCID to user data

src/pages/AssessmentEdit.tsx, src/pages/Assessments.tsx, src/types/assessment.ts
- validationID --> validation_id
- templateID --> template_id
- assessmentDoc --> assessment_doc
=> CAT-162 Update assessment fields to snake_case

src/api/services/User.ts, src/auth/KeycloakLogin.tsx, src/pages/Profile.tsx
Reverts FC4E-CAT/fc4e-cat-ui#54
=> Revert "[CAT-123] - Handle refreshing of token"

CHANGELOG.md, package.json
=> Version 0.2.0

src/pages/Validations.tsx
Enable assessments for actors:
- Manager
- Scheme
=> Enable assessments for more actors

src/pages/Validations.tsx, src/types/validation.ts
=> [CAT-184] Fix typos on validation view page

.eslintrc.cjs, package-lock.json, package.json, src/api/services/Actor.ts, src/api/services/Assessment.ts, src/api/services/Organisation.ts, src/api/services/Template.ts, src/api/services/User.ts, src/api/services/Validation.ts, src/auth/AuthContext.tsx, src/auth/KeycloakLogout.tsx, src/auth/ProtectedRoute.tsx, src/components/ActorCard.tsx, src/components/CustomTable.tsx, src/components/EvidenceURLS.tsx, src/components/Header.tsx, src/components/assessment/AssessmentTabs.tsx, src/components/tests/TestValueForm.tsx, src/pages/AssessmentEdit.tsx, src/pages/Assessments.tsx, src/pages/Profile.tsx, src/pages/ProfileUpdate.tsx, src/pages/Users.tsx, src/pages/Validations.tsx, src/types/common.ts, src/types/validation.ts, src/utils/Assessment.tsx, src/utils/Utils.tsx, vite.config.ts
- Added eslint configuration
- Fix minor lint issues
- Use Keycloak types
- Remove Type suggestions in useQuery functions and use inference instead
- Use AxiosError for errors in backend
- Handle backend errors with a util method
- Added preview specific port
- Added eslint-disable directives in CustomTable.ts until the implementation is updated accordingly
- Update pkg.json to lint before building
=> CAT-187 Add linting and corresponding fixes

src/pages/AssessmentEdit.tsx
Simplify and use only one button named SAVE. If we are in create mode the button triggers a create new assessment process. If we are in update mode the button triggers an update assessment process. Allow the button to be active at any time
=> CAT-199 Allow to save the assessment at any time

.stylelintrc.json, Jenkinsfile, package-lock.json, package.json, src/App.css, src/index.css
Install and configure stylelint module
stylelint existing css files
Add stylint check in JenskinsFile during CI/CD process
=> CAT-202 Add stylelint

src/App.tsx, src/components/Header.tsx, src/components/assessment/AssessmentInfo.tsx, src/pages/AssessmentEdit.tsx, src/pages/Assessments.tsx, src/pages/AssessmentsList.tsx, src/types/common.ts
- Add owners card in the main ASSESS view
- Reorganise tabs in create/edit assessment
- Add select actor tab in create/edit assessment view
=> [CAT-193][CAT-197][CAT-198] Update assessment view

src/pages/assessments/AssessmentEdit.tsx
- Fix the actor and organisation info on an assessment edit request
=> [CAT-205] Fix assessment edit bug

src/pages/assessments/AssessmentsList.tsx
Add required fields in user's assessment view table
=> CAT-140 Update fields in user's assessment view table

src/App.tsx, src/pages/Validations.tsx
Add approve/reject routes under admin path
Fix approve/reject cancel button navigation
Fix back button navigation when in admin view
=> CAT-224 Update validations approve/reject routes

package-lock.json, package.json, src/App.tsx, src/pages/Validations.tsx, src/pages/assessments/AssessmentEdit.tsx, src/types/common.ts
- Add react-hot-toast dependency
- Refactor notifications for validations and assessments
=> [CAT-223] Introduce notification toasts on validations

src/App.css, src/api/services/assessments.ts, src/pages/ProfileUpdate.tsx, src/pages/Validations.tsx, src/pages/assessments/AssessmentsList.tsx, src/pages/assessments/components/AssessmentInfo.tsx, src/pages/assessments/components/AssessmentSelectSubject.tsx, src/utils/common.ts
- Add an asterisk on the required form fields
- Disable subject clear button when no selection is set during assessment create
=> Required assess metadata

src/api/services/assessments.ts, src/pages/assessments/AssessmentsList.tsx
- Refactor the `useGetObjects` API call
=> Support filtering on public assessments

src/pages/assessments/AssessmentsList.tsx
Remove unnecessary header in Assessment List Table views. Add type casts where necessary
=> CAT-236 Fix double headers in tables

src/pages/assessments/AssessmentEdit.tsx
In Assessment Create/Edit view change `Cancel` button label to `Close`
=> CAT-249 Assessment edit: change cancel button to close

src/pages/Validations.tsx, src/pages/assessments/components/AssessmentInfo.tsx
Add descriptions to input types on assessment and validation create views
=> [CAT-239] Add descriptions to input types 

src/api/services/assessments.ts, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/AssessmentSelectSubject.tsx
Fixed a bug regarding name input input field reset upon browser tab
=> [CAT-233] Fix input field reset on assessment create view

src/api/services/assessments.ts, src/pages/assessments/AssessmentsList.tsx
Add option to export an assessment as a JSON file through a new action button on the assessments table
=> [CAT-237] Export assessment 

package-lock.json, package.json
Update axios, postcss and babel/traverse depedencies
=> CAT-257 update axios, postcss and babel/traverse deps

src/App.css, src/components/CustomTable.tsx, src/pages/ProfileUpdate.tsx, src/pages/assessments/components/CriteriaTabs.tsx, src/utils/common.ts
Revisit the representation of pagination on tables.
Make use of the link parameters from the backend's response json
=> [CAT-248] Revisit pagination

src/pages/assessments/AssessmentsList.tsx
Compliance badge in assessment list displayed Failed even when assessment was Unknown (null value in json). Fix compliance badge handling to cater for unknown and null values
=> CAT-259 Fix compliance badge in assessment list

src/api/services/subjects.ts, src/pages/Profile.tsx, src/pages/Subjects.tsx
Add Links to Profile page to manage objects (View List and Create new)
Add mechanism to show immediately the create new modal when following the Create new link at the profile
=> ARGO-256 Fix: Add profile link

src/pages/Subjects.tsx
In create object modal:
- Rearrange the order of Create & Cancel button
=> ARGO 256 Fix: Change order of buttons in create modal

src/App.tsx, src/pages/Profile.tsx, src/pages/Subjects.tsx
=> Refactor objects view to subjects 

src/api/services/subjects.ts, src/pages/Subjects.tsx
Give the ability to update/edit subjects and delete them
= [x] Add three modes of operation for subject modal: `Create | Update | Delete`
=> [WIP] CAT-267 Edit/Delete subjects

src/api/services/assessments.ts
Enable filtering by subject in assessment views
=> CAT-271 Fix Filters in assessment list views

cypress.config.ts, cypress/e2e/spec.cy.ts, cypress/fixtures/example.json, cypress/support/commands.ts, cypress/support/component-index.html, cypress/support/component.ts, cypress/support/e2e.ts, package.json, src/components/Header.tsx, src/pages/Profile.tsx, src/pages/ProfileUpdate.tsx
**Description**
This pull request adds Cypress to the existing project. Cypress is an end-to-end testing framework that can be used to automated testing. For now I've added two use cases from[ this document](https://docs.google.com/document/d/1EFcdQCuKRDMyledNiISeSjI_if53EUGzyD8c35lyt4E/edit?exids=71471469,71471463#heading=h.7kimagwfbht2) as tests.
**Changes Made**
- Added Cypress as a development dependency to the project.
- Created Cypress configuration files (`cypress.json`, `commands.js`, etc.).
- Created initial Cypress tests to cover the first to use cases as an example.
- Created some ids for html elements to be able to access them in the tests.
**How to setup**
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- run `npx cypress open` in the fc4e-cat-ui project.
- …
=> Added Cypress to fc4e-cat-ui

.prettierignore
Don't run prettier check in .github folder
=> add .github to prettier ignore

CHANGELOG.md, package-lock.json, package.json
Bump version to 1.0.1
Update changelog
=> Version 1.0.1

src/App.css, src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/tests/TestBinaryForm.tsx, src/pages/assessments/components/tests/TestValueForm.tsx
=> CAT-335 Update styling in create assessment wizard

src/App.css, src/pages/assessments/components/CriteriaTabs.tsx
In Assessment Edit form:
- Make sidebar have information about each criterion and its description
- Mark required criterions on the sidebar
- Show results of completed criterions on the sidebar
=> CAT-335 Further update assessment form sidebar

src/App.css, src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/CriterionProgress.tsx, src/pages/assessments/components/tests/EvidenceURLS.tsx, src/pages/assessments/components/tests/TestBinaryForm.tsx, src/pages/assessments/components/tests/TestValueForm.tsx
Add test progress in a criterion page
Simplify test section styling
=> CAT-335 Further improve assessment test styling

src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/CriterionProgress.tsx
=> CAT-335 Update stylization of test progress

src/api/services/assessments.ts
Remove public/private fetch mechanism from useGetAssessment hook
=> CAT-336 Fix error while reloading the edit assessment page

src/api/services/templates.ts
Stop refetching template data on refocus
=> CAT-294 Fix: assessment form resets on refocus

src/App.css
=> CAT-254 Fix about page style image marker

package-lock.json
=> Update follow-redirects dep

src/pages/validations/ValidationDetails.tsx
Update the way that ror id displays in validation details page
=> CAT-338 Update display of ror id in validation details

src/App.tsx, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/Assessments.tsx, src/pages/assessments/AssessmentsList.tsx, src/types/assessment.ts
Add Import mode in Assessment Editor
Create a new first stem in Assessment Wizard when importing
Add File input component to browse for a json file and import it
Filter Actor list by imported assessment actor id
=> CAT-176 Support import of external assessment

src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/Assessments.tsx, src/pages/assessments/AssessmentsList.tsx
=> CAT-352 fix export and import issues

package-lock.json, package.json, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/tests/TestBinaryForm.tsx, src/pages/assessments/components/tests/TestValueForm.tsx
- Add guidance offcanvas panel in the right side of the Assessment Edit View
- Reposition Guidance (?) buttons in Tests. 
- Make Guidance buttons open the Guidance panel. 
- If the same button is pressed again it switches the panel off. 
- If a different button is pressed it keeps the panel open and Changes contents
- Add markdown support for guidance description content
=> CAT-348 Update guidance styling

src/pages/assessments/AssessmentEdit.tsx
Minor fix in import assessment help text
=> CAT-352 Minor fix in import assessment help text

src/App.tsx, src/api/services/validations.ts, src/pages/admin/AdminUsers.tsx, src/pages/admin/AdminValidations.tsx, src/types/common.ts, src/utils/admin.ts
=> CAT-344 redesign admin view validations

src/pages/admin/AdminValidations.tsx
Add all *currently supported* pid actor types in admin validation filter element
=> CAT-344 Add all pid actor types in admin validation filter element

src/pages/admin/AdminValidations.tsx
Fix value to PID Service Provider
=> CAT-344 Fix validation actor filter service provider value

CHANGELOG.md, package-lock.json, package.json
=> prepare-v1.1.0

src/pages/ProfileUpdate.tsx
Fix regex used to validate orcids
=> CAT-379 Fix orcid validation regex

src/pages/assessments/components/tests/EvidenceURLS.tsx, src/pages/assessments/components/tests/TestBinaryForm.tsx, src/pages/assessments/components/tests/TestValueForm.tsx
Fix form submission during enter key in Tests (Removed unnecessary form element)
Added functionality: When user hits enter in Evidence field the item is added in the list
=> CAT-367 Fix key press enter issue in assessment edit view

src/pages/assessments/components/tests/TestBinaryForm.tsx
Enclose checkboxes in Form element. Deactivate Form submit event
=> CAT-388 Fix test checkboxes issue

src/pages/assessments/components/tests/TestBinaryForm.tsx
Reverts FC4E-CAT/fc4e-cat-ui#197
=> Revert "CAT-388 Fix test checkboxes issue"

src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/CriteriaTabs.tsx, src/types/assessment.ts, src/utils/assessment.ts
- Change internal type wordings to Must and Should
- Treat "Must" as the signifier for required fields
=> CAT-389 Fix marked as required criteria

src/pages/assessments/components/CriteriaTabs.tsx
Fix required label on criterion menu
=> CAT-389 Fix required label on assessment criterion menu

CHANGELOG.md, package-lock.json, package.json
prepare v1.2.1 version with fixes
=> prepare v1.2.1

src/pages/assessments/components/tests/TestBinaryForm.tsx
Add classname to test binary form
=> CAT-388 Add classname to test binary form

src/pages/assessments/components/tests/TestBinaryForm.tsx
Fix codestyling in TestBinaryForm component
=> Fix codestyling in TestBinaryForm component

src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/tests/TestBinaryForm.tsx
Display an error message when JSON format is invalid
=> CAT-391 Display error when import json format has issues

CHANGELOG.md, package-lock.json, package.json
=> prep v1.2.2

src/pages/assessments/components/tests/TestValueForm.tsx, src/types/assessment.ts
Check for `threshold_locked` instead of `locked_threshold`
=> CAT-420 Update threshold locked functionality

CHANGELOG.md, package-lock.json, package.json
=> prepare v1.2.3

src/api/services/users.ts, src/pages/assessments/AssessmentEdit.tsx
- Fix pagination query for assessment eligibility
=> CAT-436 Fix Assessment Eligibility List

src/api/services/assessments.ts, src/pages/admin/AssessmentsTable.tsx, src/types/assessment.ts
Added type filter and search bar
=> [CAT-434] - Filter the assessments by email, name, assessment ID

src/api/services/users.ts
Fix regression where AsmtEligibilityResponse type import was removed
=> Fix AsmtEligibilityResponse import in service users

src/pages/admin/AdminUsers.tsx
In Admin > Users view, remove Edit User button because the functionality doesn't exist in the backend yet
=> remove admin edit user button

src/pages/admin/ViewUsers.tsx
Add surname in User details view (Admin -> Users)
=> Display surname in admin -> users -> view user details

src/pages/admin/AdminUsers.tsx
Add user's surname to the user table
=> Add user's surname to the user table

src/pages/Profile.tsx
Reverts FC4E-CAT/fc4e-cat-ui#232
=> Revert "Update Profile.tsx"

src/components/Header.tsx
Consolidate navigation menu into a single line. Combine user and admin menus into a single dropdown button/menu
=> CAT-451 Nav menu in single line

src/App.css, src/components/Header.tsx
Remove border bottom from navigation menu
=> Fix nav menu styling - remove border bottom

src/pages/Subjects.tsx
=> [CAT-453]: add common header to all pages 

src/pages/Subjects.tsx, src/pages/assessments/Assessments.tsx, src/pages/assessments/AssessmentsList.tsx
- subjects
- assessments list when logged in
- public assessments
=> [CAT-453]: add header to all pages

src/auth/ProtectedRoute.tsx
Lowercase check when looking if the user is admin
=> CAT-454 Fix admin routing

src/App.css, src/api/services/assessments.ts, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/Comments.tsx, src/types/assessment.ts
Waiting for https://github.com/FC4E-CAT/fc4e-cat-api/pull/250
When editing an assessment give the ability to display a section where the user can add/edit comments
=> [Blocked] CAT-466 Support Assessment Comments

src/pages/validations/ValidationDetails.tsx
=> CAT-470: Update Validation request management page

src/pages/assessments/components/Comments.tsx, src/types/assessment.ts
Change user schema in comments according to the changes made in the backend.
Display user's first and last name (along with email) on comments
=> Fix user details in comments

src/pages/assessments/AssessmentEdit.tsx
- Fix issue with no displaying the correct actor info in an shared assessment
- Fix minor issue with `<p>` element inside `<p>` element in AssessmentEdit heading
- Fix minor issue with Comments and Share buttons to be available after an assessment is created
=> CAT-461 Fix view actor in shared assessment issue

src/pages/Subjects.tsx
removed sorting since it is not supported by the api
=> CAT-457: User Subjects should follow the same table approach as admin

src/pages/Profile.tsx, src/pages/validations/ValidationDetails.tsx
Replace user profile image with user icon - colored based on user id hash
=> CAT-488 Update user avatars in profile and validation details pages

src/pages/assessments/AssessmentsList.tsx
Add `shared` badge for shared assessments in assessments list page
=> CAT-489 Show shared badge in assessments list

src/App.css, src/pages/admin/ViewUsers.tsx
=> CAT-371:[UI] - Admin - View User

CHANGELOG.md
=> minor lintfix in CHANGELOG.md

src/App.tsx, src/api/services/motivations.ts, src/components/Header.tsx, src/pages/motivations/Motivations.tsx, src/types/index.ts, src/types/motivation.ts
=> CAT-494 Display list of motivations

src/App.tsx, src/api/services/motivations.ts, src/pages/motivations/MotivationDetails.tsx, src/pages/motivations/Motivations.tsx, src/pages/motivations/components/MotivationActorModal.tsx, src/pages/motivations/components/MotivationModal.tsx, src/types/motivation.ts
Display motivation details
Add actor to motivation
Update motivation info
=> CAT-494 Display motivation Details. CAT-497 Add actor to motivation

src/App.tsx, src/pages/assessments/AssessmentView.tsx, src/pages/assessments/AssessmentsList.tsx
A simple view page to display assessment results
=> CAT-520 View assessment results

src/api/services/motivations.ts, src/pages/motivations/MotivationActorCriteria.tsx, src/types/criterion.ts, src/types/motivation.ts
=> CAT-517 Manage Criteria for specific assessment type update

src/pages/motivations/MotivationDetails.tsx
Reinstate MotivationDetails component
=> CAT-542 Reinstate MotivationDetails component

src/pages/assessments/AssessmentView.tsx
In Assessment View make statistics to be calculated dynamically from the assessment
=> CAT-544 Make Assessment View statistics dynamic

src/pages/assessments/AssessmentsList.tsx
Remove filter toggle functionality from assessment list
=> CAT-553 Remove filter toggle functionality from assessment list

src/pages/assessments/AssessmentsList.tsx
=> CAT-456 - User Assessments should follow the same table approach . 

src/api/services/motivations.ts, src/pages/motivations/Motivations.tsx, src/types/common.ts
Enable search in motivations page
=> CAT-561 Enable search in motivations list

src/pages/motivations/components/MotivationModal.tsx
Fix motivation type id reference
=> CAT-557 Update motivation-type-id in update motivation details modal

src/pages/assessments/AssessmentsList.tsx
=> Update share icon

src/pages/assessments/AssessmentsList.tsx
Use link to alternative path when assessment is public
=> CAT-562 Link to correct path for public assessment results

src/App.css, src/pages/motivations/MotivationDetails.tsx
- Add Tabs in motivation details page
- Make Assessment Types tab the default one
- Add provided stylization
=> CAT-574 Tabs in motivation details

src/api/services/motivations.ts, src/pages/motivations/MotivationDetails.tsx, src/pages/motivations/components/MotivationCriteria.tsx, src/pages/motivations/components/MotivationPrinciples.tsx
In motivation details view add two lists
- List of principles (under this motivation)
- List of criteria (under this motivation)
Each list is displayed in it own tab view
=> CAT-575 Add Principles & Criteria lists in Motivation Details view

src/pages/assessments/AssessmentView.tsx, src/pages/assessments/AssessmentsList.tsx, src/pages/assessments/MotivationAssessmentEditor.tsx, src/pages/motivations/MotivationActorCriteria.tsx, src/pages/motivations/components/MotivationPrinciples.tsx
- Assessment table added col-lg-1, col-lg-2 to date and actions so as not to wrap
- Preview assessments ui fixes
- colour suggestions for the statistics and the same colour at the denominator of the fractions 
- Swapped the “passed” stamp and “details” box position
- Added a “date last updated” under the “details” section
=> various fixes

src/pages/motivations/MotivationDetails.tsx
In motivation added comments in buttons that are not used
=> Small fixes

src/pages/motivations/Motivations.tsx
Reset pagination when user actively searches something
=> CAT-578 fix motivations search and pagination

CHANGELOG.md, package-lock.json, package.json
=> prep version v2.0.0

src/auth/ProtectedRoute.tsx
Add procedure to check for token expiration and call refresh
=> CAT-528 Check for token expiration and refresh

src/auth/ProtectedRoute.tsx
=> Revert "CAT-528 Check for token expiration and refresh"

src/App.tsx, src/api/index.ts, src/api/services/criteria.ts, src/api/services/motivations.ts, src/api/services/principles.ts, src/components/Header.tsx, src/config.json, src/config.tsx, src/pages/criteria/Criteria.tsx, src/pages/criteria/CriterionDetails.tsx, src/pages/criteria/components/CriterionModal.tsx, src/pages/motivations/MotivationActorCriteria.tsx, src/pages/motivations/MotivationCriteriaPrinciples.tsx, src/types/criterion.ts
=> CAT-597 Criteria Management as admin

src/App.css, src/App.tsx, src/auth/ProtectedRoute.tsx, src/components/AdminMenu.tsx, src/components/Header.tsx, src/pages/assessments/Assessments.tsx, src/pages/criteria/Criteria.tsx, src/pages/criteria/CriterionDetails.tsx, src/pages/motivations/MotivationCriteriaPrinciples.tsx, src/pages/motivations/MotivationDetails.tsx, src/pages/motivations/Motivations.tsx, src/pages/principles/PrincipleDetails.tsx, src/pages/principles/Principles.tsx
Add admin menu sidebar on admin pages to make navigation more easy
=> CAT-606 Add admin sidebar menu in admin views

src/pages/assessments/AssessmentEdit.tsx, src/pages/motivations/MotivationDetails.tsx
Update url paths when tabs change
=> CAT-602 Update url path hashes when tabs change

src/App.css, src/auth/ProtectedRoute.tsx, src/components/AdminMenu.tsx, src/pages/About.tsx, src/pages/Home.tsx
=> CAT-624 center admin view layout

src/api/services/motivations.ts, src/pages/motivations/MotivationDetails.tsx
Allow user to delete Assessment types (actors) from a specific motivation
=> CAT-611 Delete asssessment type (actor) from motivation

src/api/services/principles.ts
Add missing `/v1/` prefix in path
=> CAT-658 Fix delete principle backend path regression

src/pages/motivations/components/MotivationPrinciples.tsx
Create principle button should appear always
=> CAT-658 Fix create principle button in motivations

src/pages/assessments/AssessmentView.tsx
Fix assessment mandatory check with `MUST` value instead of old `must`
=> CAT-677 Fix regression in report mandatory statistics

src/pages/motivations/MotivationDetails.tsx, src/pages/motivations/components/MotivationCriteria.tsx, src/pages/motivations/components/MotivationPrinciples.tsx
=> CAT-655 Add publish/unpublish button in motivation details

src/pages/assessments/AssessmentPdf.tsx, src/pages/assessments/AssessmentsList.tsx, src/pages/assessments/components/AssessmentEvalStats.tsx
Remove ranking from assessment report, pdf and list
=> CAT-676 Remove Ranking

src/pages/admin/AdminValidations.tsx
For filter values dropdown: replace hardcoded list of actors with dynamic list of registry actors
=> CAT-674 Update actor filter in admin validations view

src/api/services/motivations.ts, src/pages/motivations/components/MotivationCriMetric.tsx, src/pages/motivations/components/MotivationCriteria.tsx, src/pages/motivations/components/MotivationMetricAssignModal.tsx, src/types/motivation.ts
Under motivation, allow a user to assign a metric to a specific criterion
=> CAT-700 assign metric to criterion (under motivation)

src/api/services/registry.ts, src/pages/motivations/MotivationMetricTests.tsx, src/pages/motivations/components/MotivationTestModal.tsx, src/types/tests.ts
Implement new modal that allows user to enter info for creating new test
=> CAT-704 Create new test

src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/tests/TestValueFormParam.tsx
Fix principle label in edit assessment page
Fix disclaimer text in automated test
=> CAT-707 minor i18n fixes

src/assets/locales/en.json, src/pages/criteria/components/CriterionModal.tsx, src/pages/motivations/components/MotivationMetricModal.tsx, src/pages/motivations/components/MotivationTestModal.tsx
Minor fixes in i18n labels used in motivation views
=> CAT-717 Fix motivations i18n issues

src/components/AdminMenu.tsx, src/pages/motivations/Motivations.tsx
- Motivations table had an issue with hover. Removed css from each td [CAT-716] 
- Motivations table columns width changes. Added className to column description <th className="w-50 p-3"> to help with the view. Under investigation with @kaggis 
- Admin menu had an error in assessments admin page path.
=> CAT-715: Various small fixes 

src/api/services/motivations.ts, src/pages/motivations/components/MotivationTestModal.tsx
Update create-metric backend path. 
Update create test modal to clean input values when reappears
=> CAT-721 Update create-metric backend path.

src/pages/validations/ValidationDetails.tsx, src/pages/validations/ValidationList.tsx
- Validation Requests list missing actor type
- Validation Requests view missing actor type
=> CAT-711 CAT-712: Validation Requests list, view missing actor type

src/assets/locales/en.json, src/pages/assessments/components/CriteriaTabs.tsx, src/pages/assessments/components/tests/TestAutoMd1Form.tsx, src/pages/motivations/MotivationDetails.tsx, src/pages/motivations/components/MotivationActorModal.tsx, src/pages/motivations/components/MotivationCriMetric.tsx, src/types/assessment.ts, src/types/common.ts
=> Support auto md1 validation tests in assessments

src/pages/assessments/components/tests/TestAutoMd1Form.tsx
Conditional to have message text stylized based on test result (success = green, fail = red)
=> CAT-742 Update auto-md1 test message text styling

src/App.tsx, src/api/services/criteria.ts, src/api/services/motivations.ts, src/api/services/principles.ts, src/api/services/registry.ts, src/assets/locales/en.json, src/components/AdminMenu.tsx, src/pages/motivations/MotivationMetricTests.tsx, src/pages/tests/Tests.tsx, src/pages/tests/components/TestModal.tsx, src/types/common.ts, src/types/tests.ts
Add new administrative view to manage tests in the system
=> CAT-736 Add library of tests view

src/api/services/registry.ts, src/assets/locales/en.json, src/pages/motivations/MotivationMetricTests.tsx, src/pages/tests/Tests.tsx, src/pages/tests/components/TestModal.tsx, src/types/tests.ts
Give the ability to view details of a test item and also update it
=> CAT-747 View/update test

src/api/services/registry.ts
Update list of all tests inside motivation view after a new test has been created
=> CAT-748 Update list of tests in motivation after test creation

codemeta.json
=> lint codemeta json

src/assets/locales/en.json, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/AssessmentPdf.tsx, src/pages/assessments/AssessmentView.tsx, src/pages/assessments/AssessmentsList.tsx, src/pages/assessments/components/AssessmentEvalStats.tsx
Add assessment ranking. Ranking is calculated as the percentage of number of optional criteria passed / total optional criteria
=> CAT-740 Reintroduce ranking

codemeta.json
=> add codemeta.json

src/App.tsx, src/api/services/registry.ts, src/assets/locales/en.json, src/components/AdminMenu.tsx, src/pages/metrics/Metrics.tsx, src/pages/metrics/components/MetricModal.tsx, src/types/index.ts, src/types/registry.ts
=> CAT-751 Add metrics to library

src/api/services/registry.ts, src/pages/Home.tsx, src/types/common.ts
=> CAT-789 Display statistics in welcome page

src/pages/assessments/AssessmentPdf.tsx, src/pages/assessments/AssessmentView.tsx, src/pages/assessments/AssessmentsList.tsx, src/pages/assessments/components/AssessmentEvalStats.tsx, src/utils/common.ts
Display ranking with two fixed decimal digits
=> CAT-787 Display ranking with two fixed decimals

src/assets/locales/en.json, src/pages/assessments/AssessmentEdit.tsx, src/pages/assessments/components/ShareModal.tsx
=> CAT-784 Fix share i18n issue

src/components/PublishModal.tsx
Minor i18n fix on publish assessment notifications
=> CAT-811 Minor i18n fix on publish assessment notifications

src/pages/Profile.tsx, src/pages/admin/AdminAssessments.tsx
Add copy to clipboard button for user ids in Assement List table for admin
=> CAT-813 Add copy user id button in view assessments list for admins

src/assets/locales/en.json, src/pages/admin/AdminUsers.tsx
Fix tooltips in user admin page
=> CAT-587 Fix tooltips in user admin page

CHANGELOG.md, package-lock.json, package.json
=> bump v3.1.0
