src/config.json
src/keycloak.json

Make cat-ui by default to work with local backend (cat-api at 8080) and local keycloak (58080 with default quarkus realm config)

CAT-61 Use local backend and keycloak by default

---

src/App.tsx
src/api/services/Template.ts
src/api/services/Validation.ts
src/components/Header.tsx
src/components/assessment/AssessmentInfo.tsx
src/pages/AssessmentEdit.tsx
src/pages/Validations.tsx
src/types/assessment.ts

Add a new view to the ui allowing the user to create a new assessment. For the time being the process is initiated from the Validation list view. Each approved validation has a `+ Assessment` button that redirects to the new create assessment view. The view displays a header with general information for the assessment such as id, name, organisation, type. This view is implemented as a separate component with all the required props and it is used by the AssessmentEdit page

CAT-98 Display assessment header information

---

src/App.css
src/components/assessment/AssessmentTabs.tsx
src/components/tests/TestBinary.tsx
src/index.tsx
src/pages/AssessmentEdit.tsx
src/types/assessment.ts
src/utils/Assessment.tsx

Give the ability to evaluate criteria metrics and the whole assessment compliance and ranking while the user interacts and fills-in the tests
- `evalMetric` accepts a criterion metric and the included tests and calculates its value based on the algorithm and benchmark provided. ⚡ this Function is called when handling changes in the assessment state
- `evalCriteria` accepts an assessment and calculates the compliance and the ranking (and some stats) by examining all included criteria. ⚡ this Function is called before rendering the assessment view

CAT-Add dynamic evaluation of assessment and provide statistics

---

src/App.css
src/App.tsx
src/api/services/Assessment.ts
src/api/services/Validation.ts
src/components/Header.tsx
src/components/tests/TestBinary.tsx
src/pages/AssessmentEdit.tsx
src/pages/Assessments.tsx
src/pages/Home.tsx
src/pages/Profile.tsx
src/pages/Users.tsx
src/pages/Validations.tsx
src/types/assessment.ts

... Add simple assessment list
Allow the user to create a new assessment or update an existing one. After creating / updating the user will be redirected to a list of assessments view

CAT-103 Add functionality to store/update an assessment. 

---

src/api/services/Assessment.ts
src/pages/AssessmentEdit.tsx

Assessment IDs are stored as a UUID, but frontend assumes a number. This PR fixes the bugs that occur from this outdated assumption.

Fix bug with assessment id on edit

---

src/api/services/assessments.ts

A user tries to update an assessment. The updated changes are not reflected instantly in the ui due to caching issues. This is caused because the assessment id has changed from integer to string and the update backend process handles it wrongly. 
During the update backend call, handle the assessment id as a string when issuing a cache key for react query

CAT-200 Fix assessment update regression due to changes in assessment id

---

src/pages/assessments/components/CriteriaTabs.tsx

Fix: Don't set active tab key if it's already been set

CAT-204 Fix interaction issue in criteria tabs

---

src/pages/assessments/AssessmentsList.tsx

CAT-206 Fix public assessment table columns. Fix create new button

---

src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/components/CriteriaTabs.tsx

Step 1. In create assessment wizard > first tab (actor) select an actor/org to start assessing
Step 2. While in first tab select again a different actor/org that loads a new assessment
Step 3. Go to the third step (assessment view). The first criterion is not selected by default

CAT-207 Fix select first criterion tab as active in assessment wizard

---

src/App.css
src/pages/assessments/AssessmentsList.tsx

Add the following fields in public assessment table:
- name
- type
- subject name
- subject type
- organisation
- created_on
The date on created_on column should be in YYYY-MM-DD. Added also an info icon that appears when user hovers over the date and allows to display a tooltip with the full date

CAT-212 Public assessment table fields

---

src/App.tsx
src/components/CustomTable.tsx
src/components/Header.tsx
src/pages/Users.tsx
src/pages/Validations.tsx
src/types/validation.ts

1) Move admin related views under `/admin/` routing path
for example:
`/users` 👉  `/admin/users`
2) Validations are accessed both by users and admins. Users see their own personal validation requests, admins see all requests. Keep `/validations` path for users but add also `/admin/validations` path for admins
3) Make each admin page more prominent by adding a blue hue heading in admin/users and admin/validations views in order for admins to discern quickly that they are managing something as administrators instead of plain users
4) Update various links accordingly to point to the new `/admin/...` destinations
6) Small fix in TableViews (assessments, users, validations) column definitions that removes an unnecessary top table empty header

CAT-216 Organise admin views

---

src/pages/assessments/components/tests/TestValueForm.tsx

In Tests that receive values input boxes accept only numbers

CAT-225 Restrict test value input boxes to numbers

---

src/auth/ProtectedRoute.tsx

Solves the issue with the unnecessary renegotiation of keycloak (thus, rendering delays) when jumping from unprotected to protected routes.

Fix multiple calls on keycloak init

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentsList.tsx

Added requested functionality to have a Save button that saves the assessment without exiting the view and a Submit button that is activated when all fields are filled-out and compliance has been calculated. The Submit button saves the assessment and redirects to the assessment list view
On the creation process we have replaced the Save button with Create because it needs to do a create action that will generate the new assessment and assign it a new id. Then the user can move on to edit it and have the save/submit button capability
Implementation

CAT-230 Save/Submit functionality in assessment

---

src/pages/Validations.tsx

Rearrange create validation form to hold more fields per row
Implementation:

CAT-234 Rearrange create validation request form

---

src/api/services/assessments.ts
src/components/DeleteModal.tsx
src/pages/assessments/AssessmentsList.tsx
src/types/assessment.ts

CAT-226 Implement delete assessment

---

src/pages/assessments/AssessmentsList.tsx

Format text when exporting JSON so that you'll get something like:
```
{
"id": "901aa669-fa8e-4736-a3f9-cadc281d9f54",
"user_id": "alice_voperson_id",
"validation_id": 31,
"created_on": "2023-11-14 14:54:39.515812",
"updated_on": "",
"template_id": 4,
"assessment_doc": {
"name": "cvcvcvcv",
"version": "",
"status": "",
...
```
instead of a compressed single line output like:
```
{ "id": "901aa669-fa8e-4736-a3f9-cadc281d9f54", "user_id": "alice_voperson_id", ...
```

CAT-258 Format exported JSON

---

src/pages/assessments/AssessmentEdit.tsx

Fix the bug related to faulty actor change during assessment creation. Now assessment principles on last tab of the wizard are updated according to the actor change.

[CAT-260] Elaborate on faulty actor changes in the assessment

---

src/components/CustomTable.tsx
src/pages/assessments/AssessmentsList.tsx

Each table definition has an already declared `header` property that includes the column label in a `span` element. 
- Use these definitions when rendering the table headers. 
- Fix some of these definitions in Assessment List table in order to have capitalized first letters. 
- This automatically fixes the column labels in the Subjects table

ARGO-283 Refactor handling of table headers

---

src/api/services/subjects.ts
src/pages/assessments/components/AssessmentInfo.tsx
src/pages/assessments/components/AssessmentSelectSubject.tsx
src/types/assessment.ts
src/types/common.ts

Update the select subject component in step 2 of the create/edit assessment form. The component should load now the subjects provided by the GET `/api/subjects` backend call. Also when an existing subject is selected it should update the assessment json to include a db_id reference under subject object

CAT-272 Update subject list in step2 of assessment creation

---

src/api/services/validations.ts
src/pages/Validations.tsx
src/pages/assessments/AssessmentEdit.tsx
src/types/validation.ts

CAT-310 Fix validation details requests for admin and non-admin views

---

cypress/e2e/profile.cy.ts
cypress/fixtures/profile_empty.json
cypress/fixtures/profile_updated.json
src/pages/Profile.tsx

This PR adds a spec that tests both the /profile and the /profile/update pages. It checks that the links are working or hidden depending on the state of the users profile info. It also tests the profile update form.
- Added tests for the /profile page
- Added tests for the /profile/update page
- Added ids for selecting certain fields in the profile page.
- Added ids for checking if a field was hidden.
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- run `npx cypress open` in the fc4e-cat-ui project.
- Select E2E testing.
- Select a browser and click 'start testing'.
- This should open the chosen browser and allow you to run the test by clicking on 'assessment.cy.ts'.
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- `npx cypress run`

Cypress profile test

---

cypress/e2e/subject.cy.ts
cypress/fixtures/subjects/subject.json
cypress/fixtures/subjects/subject_deleted.json
cypress/fixtures/subjects/subject_edit.json
cypress/fixtures/subjects/subjects.json
src/pages/Subjects.tsx

This PR adds a spec for testing the /subjects and the /subjects?create pages. It tests the subjects?create form and the editing and deleting of subjects.
- Added tests for the /subjects page
- Added tests for the /subjects?create page
- Added id for button that closes modal.
- Added dynamic ids for the subject edit and delete button in the subjects table.
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- run `npx cypress open` in the fc4e-cat-ui project.
- Select E2E testing.
- Select a browser and click 'start testing'.
- This should open the chosen browser and allow you to run the test by clicking on 'assessment.cy.ts'.
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- `npx cypress run`

Cypress subject page test

---

src/App.tsx
src/pages/validations/ValidationDetails.tsx

CAT-326 Fix admin validation details view information backend path 
CAT-327 Turn approve/reject dialogs into modals

CAT-323 Fix approve/reject admin validation paths

---

src/pages/assessments/AssessmentEdit.tsx

The validated actors list is compiled by fetching first the approved validation requests from the api. When fetch the first page of the approved validation request replace local ui data with the result. When fetching further pages add them to the local data result. Fix also hook dependencies

CAT-328 Assessment creation: fix issue with valid actor duplicates

---

src/components/Header.tsx
src/pages/assessments/Assessments.tsx

Simplify the navigation menu by removing unused placeholder items
- `PROFILE`, `VALIDATIONS`, `ASSESSMENTS` when user is logged in
- `ASSESSMENTS` when user is logged out

CAT-329 Simplify navigation menu

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/components/AssessmentInfo.tsx
src/pages/assessments/components/AssessmentSelectSubject.tsx
src/pages/assessments/components/CriterionProgress.tsx
src/pages/validations/RequestValidation.tsx

CAT-302 Improve error notifications in assessment create form

---

cypress/e2e/assess.cy.ts
cypress/e2e/assessment.cy.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/Assessments.tsx
src/pages/assessments/AssessmentsList.tsx
src/pages/assessments/components/ActorCard.tsx

This PR adds the assess spec and updates the assessment spec. The assess spec, assess.cy.ts, tests the /assess page. It check all interaction on the page like the links and the actor cards. The assessment spec has been extended with tests for the editing and deleting of an assessment. It also now tests the filter functionality for the assessment table.
I've also added dynamic ids for the actor cards and for the action buttons in the assessment table. Please have a look if you agree with the way these dynamic ids are generated.
- Added a spec for testing the /assess page.
- Updated assessment spec to include tests for /assessment page functionality.
- Added ids for selecting elements to use in the specs.
- Added dynamic ids for the actor cards and assessment table actions.
- Setup and run …

Cypress spec /assess and /assessment page

---

src/App.css
src/App.tsx
src/api/services/users.ts
src/pages/Users.tsx
src/pages/admin/AdminUsers.tsx
src/types/common.ts

CAT-343 redesign admin users view

---

src/App.tsx
src/components/Header.tsx
src/config.json
src/pages/Explore.tsx

Add a new 'Explore' view that hosts external results through an iframe (we can change 'Explore' name to whatever we want)
External view is configured through config.json

CAT-380 Add iframe

---

src/pages/assessments/components/AssessmentSelectSubject.tsx

Restrict subject id, name and type input fields (in create/edit assessment view) to accept 200 characters max

CAT-378 Restrict subject input fields to 200 chars max

---

src/pages/admin/AdminUsers.tsx

When an admin tries to delete/restore a user the modal now displays also the user name

CAT-382 Add user name in delete/restore modal

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentsList.tsx

Make useGetAssessment hook work in private and public mode. When in public mode the useGetAssessment hook uses a different api endpoint (`/assessments/public/{id}`) to get a specific assessment that is available publicly. 
Use the hook accordingly to the AssessmentList component by examining the prop (isPublic). IsPublic is true when we are displaying a public assessment view list. 
In the case of AssessmentEdit component the mode is always private so we set isPublic to always false

CAT-390 make Public Assessment download button work without login

---

src/pages/assessments/components/tests/TestValueForm.tsx
src/types/assessment.ts

This should be merged after: https://github.com/FC4E-CAT/fc4e-cat-api/pull/214
When a value test has the `locked_threshold: true` parameter the corresponding input box in assessment editor is locked along with a corresponding info message

CAT-420 support for locked thresholds

---

package-lock.json
src/App.tsx
src/api/services/assessments.ts
src/api/services/templates.ts
src/api/services/users.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/components/AssessmentSelectActor.tsx
src/pages/assessments/components/tests/TestValueForm.tsx
src/types/assessment.ts

Based on cat-api changes introduced here: 
https://github.com/FC4E-CAT/fc4e-cat-api/pull/224
~⚠️ WARNING: to be merged after the above PR ☝️~ *merged*
Support for different assessment types when creating/editing/importing assessments

CAT-427 Support multiple assessment types

---

src/pages/assessments/AssessmentEdit.tsx

Create a temp list that catches all items by browsing the returned pages from `/users/assessment-eligibility` call. When the temp list is filled used to store the items to the actorMap state variable

CAT-436 Fix Assessment Eligibility List duplicate items

---

src/pages/assessments/components/tests/EvidenceURLS.tsx

- Open evidence links to a new tab
- Change evidence link icons to that of an External Link Icon (more clear intention)

CAT-392 Open evidence url in new tab

---

src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentsList.tsx
src/types/assessment.ts

Add a label `shared with me` when an assessment appears on my list as a share from another user. The label is displayed both in the assessments view and in the edit assessment tab

CAT-447 Add shared with me label to assessments

---

src/auth/ProtectedRoute.tsx

When an non-admin user tries to access a path that leads to an admin-view, redirect to the profile page

CAT-365 Redirect when non-admin users try to access admin paths

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentsList.tsx
src/pages/assessments/components/ShareModal.tsx
src/types/assessment.ts

Support sharing of assessments between users

CAT-446 Support assessment sharing

---

src/auth/ProtectedRoute.tsx
src/pages/admin/AdminUsers.tsx

- Fix view user details button to be an actual react-router link element 
- When checking if user is eligible to follow an admin route, check only if you have at hand the user profile data to check for admin value

CAT-469 Fix admin view users link and admin route checks

---

src/api/services/validations.ts
src/pages/validations/ValidationDetails.tsx
src/types/validation.ts
style_script

CAT-383 Reason for rejection of a validation

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentsList.tsx
src/types/assessment.ts

- Update assessment type schema to retrieve `shared: boolean` attribute
- Make share buttons green in assessment list when an assessment has `shared: true`
- Simplify react query assessment list caching keys to refresh assessment list when something becomes shared

CAT-471 Emphasize shared assessments in assessments list

---

src/api/services/motivations.ts
src/pages/motivations/Motivations.tsx
src/pages/motivations/components/MotivationModal.tsx
src/types/motivation.ts

Allow user to create new motivation items

CAT-495 Create new motivation

---

src/App.tsx
src/api/services/principles.ts
src/components/DeleteModal.tsx
src/components/Header.tsx
src/pages/assessments/components/CriteriaTabs.tsx
src/pages/motivations/MotivationDetails.tsx
src/pages/principles/PrincipleDetails.tsx
src/pages/principles/Principles.tsx
src/pages/principles/components/PrincipleModal.tsx
src/types/assessment.ts
src/types/index.ts
src/types/principle.ts

Support
- Viewing list of principles
- View Principle details
- Update Principle details
- Create new Principle
- Delete Principle
- Convert old principe type to AssessmentPrinciple to distinguish it and avoid conflicts with new Principle type declarations
- Implement Principle related types
- Implement Principle related backend service query/mutation hooks (create, read, update, delete)
- Implement Principles component to display list of principles
- Implement PrinciplesDetails component to display detailed view of a principle
- Implement PrincipleModal to insert/edit details for a principle
- Use DeleteItem Modal to confirm deletion of a principle
- Minor cleanup and fixes (back button, delete icon)

Support crud of principles

---

src/api/services/motivations.ts
src/config.json
src/config.tsx
src/pages/motivations/MotivationDetails.tsx
src/pages/motivations/components/MotivationPrincipleModal.tsx
src/types/motivation.ts

When viewing a motivation's details show the connected principles and allow user to connect additional ones.

CAT-510 Add principles to motivations

---

src/pages/assessments/components/tests/EvidenceURLS.tsx

Trim the input value on Evidence URL field before validating

CAT-521 Fix evidence url validation - trim input

---

src/api/services/motivations.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentView.tsx
src/pages/assessments/components/CriteriaTabs.tsx
src/pages/motivations/MotivationActorCriteria.tsx
src/types/assessment.ts
src/types/criterion.ts
src/types/motivation.ts
src/utils/assessment.ts

CAT-546 Select Imperative when adding new Criteria to Assessment Type

---

src/api/services/assessments.ts
src/pages/assessments/AssessmentsList.tsx
src/types/assessment.ts

CAT-555 Fix share badges in new Assessment Table

---

src/api/services/motivations.ts
src/pages/motivations/MotivationDetails.tsx
src/pages/motivations/Motivations.tsx
src/pages/motivations/components/MotivationModal.tsx
src/types/motivation.ts

Give the ability to the user to create a new motivation based on a previous one (clone)

CAT-545 Add clone motivation button

---

src/pages/assessments/AssessmentView.tsx

- Ranking is derived from optional: remain same colour? 
- Mandatory number green.
- Move the “assessment for” to the header and remove the (assessment)ID? 
- Must label text color changed 
- Aligned the must/should/may and pass/fail to the right,
- Remove “type" from subject
- Bigger fonts

CAT-529: Wilko comments

---

src/App.css
src/App.tsx
src/api/services/templates.ts
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/AssessmentView.tsx
src/pages/assessments/MotivationAssessmentEditor.tsx
src/pages/assessments/components/AssessmentEvalStats.tsx
src/pages/assessments/components/CriteriaTabs.tsx
src/pages/motivations/MotivationDetails.tsx
src/types/assessment.ts
src/utils/assessment.ts

Allow to view a working Assessment Preview for each Assessment Type under Motivation
Warning: Value tests input doesn't work because the schema has diverged a lot from the old one. We need to revisit that

CAT-549 View Assessment per Assessment Type in Motivation Details

---

src/pages/assessments/components/CriteriaTabs.tsx
src/pages/assessments/components/tests/EvidenceURLS.tsx
src/pages/assessments/components/tests/TestBinaryParam.tsx
src/types/assessment.ts

Support list of parameters given in new Binary Tests and display info on test forms

CAT-567 In BinaryTests manage list of params and tooltips given

---

src/pages/assessments/components/CriteriaTabs.tsx
src/pages/assessments/components/tests/TestBinaryParam.tsx
src/pages/assessments/components/tests/TestToolTip.tsx
src/pages/assessments/components/tests/TestValueFormParam.tsx
src/pages/assessments/components/tests/index.ts
src/types/assessment.ts

Handle correctly parameters in new Value Tests

CAT-568 Manage parameters in Value Tests

---

src/App.css
src/pages/assessments/components/CriteriaTabs.tsx

Avoid scrolling up and down between criteria tabs and test content
Add a max height of 80% of the viewport for the active assessment content (criteria and tests). Add scroll bars to these two columns (list of criteria / list of tests for each criterion). Since the criteria are displayed as tabs that change the content of the tests try to add their scrollbar to the left side to maintain the visual appearance of a tab view (even thought the tabs scroll). Might seem a bit off for some users - feedback needed

CAT-525 Avoid scrollups between criteria tabs and test content

---

src/App.css
src/App.tsx
src/api/services/motivations.ts
src/config.json
src/config.tsx
src/pages/motivations/MotivationCriteriaPrinciples.tsx
src/pages/motivations/MotivationDetails.tsx
src/pages/motivations/components/MotivationPrinciplesModal.tsx
src/types/motivation.ts

Allow user to define which criteria and principles take part in a specific Motivation. User selects the criteria and connects them with principles that describe them.

CAT-591 Manage motivation's criteria and principles

---

src/api/services/actors.ts
src/api/services/validations.ts
src/pages/validations/RequestValidation.tsx
src/types/common.ts
src/types/validation.ts

Validation Requests should use the new actor ids (example: `pidgraph:333990)

CAT-581 Use new actor ids in validations

---

package-lock.json
package.json
src/App.tsx
src/api/client.ts
src/api/services/actors.ts
src/api/services/assessments.ts
src/api/services/criteria.ts
src/api/services/motivations.ts
src/api/services/organisations.ts
src/api/services/principles.ts
src/api/services/subjects.ts
src/api/services/templates.ts
src/api/services/users.ts
src/api/services/validations.ts
src/pages/ProfileUpdate.tsx
src/pages/assessments/AssessmentEdit.tsx
src/pages/assessments/components/AssessmentSelectActor.tsx
src/types/assessment.ts

- In Assessment Editor wizard updated Step-1 list to fetch new assessment-types (actor-motivations)
- Created two query hooks for fetch templates (one for admins, one for verified users)
- Updated assessment evaluation methods in step-3 of the editor
- API client used the `/v1` prefix from config.json - that meant that backend calls could only be made on one version of the api. Removed the preconfigured prefix and declared it as a part of the path of each method. This allows to make calls to both /v1 and /v2 endpoints
- Updated CREATE, READ, DELETE assessment methods to use /v2/assessment backend calls
- Updated assessment list components to use /v2/assessment methods
⚠️ Breaking-Changes: 
What needs to be updated on the backend to work with the new assessments (/v2):
- …

CAT-582 Support new actors and motivations in assessment editor

---

src/api/services/assessments.ts

Update backend hook `useUpdateAssessment` to use the new /v2/ version of the cat-api call

CAT-628 Use new assessment update call

---

src/api/services/actors.ts
src/api/services/assessments.ts
src/pages/assessments/AssessmentView.tsx
src/pages/assessments/Assessments.tsx
src/pages/assessments/AssessmentsList.tsx
src/types/common.ts

Update backend calls to fetch objects for public and non-public assessments. Update assess page to show v2 public assessment per v2 actors

CAT-634 Update backend calls for objects for v2 assessments

---

src/App.css
src/api/services/motivations.ts
src/pages/motivations/MotivationDetails.tsx
src/pages/motivations/Motivations.tsx
src/types/motivation.ts

Allow user to publish/unpublish motivations. Also allow the user -under a motivation- to publish/unpublish assessment types (Motivation-Actor items)

CAT-630 Toggle publish in motivations and assessment types

---

src/pages/assessments/components/CriteriaTabs.tsx
src/pages/assessments/components/tests/TestAutoHttpsCheckForm.tsx
src/types/assessment.ts
src/types/common.ts

Support in UI tests that are of `Auto-Check-Url-Binary` type that allow a user to enter a url and check if it indeed a valid https endpoint

CAT-639 Add support for automated https check test

---

src/api/services/motivations.ts
src/pages/motivations/components/MotivationPrinciples.tsx
src/pages/principles/components/PrincipleModal.tsx
src/types/motivation.ts

Give the ability to the user to quickly add a new principle under a motivation. This principle will also be available in the principle library

CAT-615 Add Principle under motivation

---

src/api/services/motivations.ts
src/pages/motivations/components/MotivationCriMetric.tsx
src/pages/motivations/components/MotivationCriMetricModal.tsx
src/pages/motivations/components/MotivationCriteria.tsx
src/types/criterion.ts

In motivation -> criteria, show for each criterion information about it's metric and tests

CAT-587 Show Criteria Metrics in Motivation

---

src/api/services/criteria.ts
src/pages/criteria/components/CriterionModal.tsx
src/pages/motivations/MotivationCriteriaPrinciples.tsx
src/pages/motivations/MotivationDetails.tsx
src/pages/motivations/components/MotivationCriteria.tsx
src/pages/motivations/components/MotivationPrinciplesModal.tsx

Move manage criteria button to the criteria tab. Update manage criteria view to allow to add new criteria. Allow only one principle to each criterion

CAT-663 Allow to add new criteria when managing them in a motivation

---

src/pages/assessments/AssessmentPdf.tsx
src/pages/assessments/AssessmentView.tsx
src/types/assessment.ts

CAT-678 Fix Assessment View and PDF errors

---

src/App.tsx
src/api/services/motivations.ts
src/api/services/registry.ts
src/config.json
src/config.tsx
src/pages/motivations/MotivationMetricTests.tsx
src/pages/motivations/components/MotivationMetrics.tsx
src/types/motivation.ts
src/types/tests.ts

Give the ability to assign tests to metrics

CAT-701 Assign tests to metrics

---

src/api/services/motivations.ts
src/assets/locales/en.json
src/pages/motivations/components/MotivationCriteria.tsx
src/pages/motivations/components/MotivationMetric.tsx
src/pages/motivations/components/MotivationMetricAssignModal.tsx
src/pages/motivations/components/MotivationMetricDetailsModal.tsx
src/pages/motivations/components/MotivationMetrics.tsx

Allow to view metric details with included tests for a specific metric. Use the same modal as with criterion -> metric details.

CAT-732 Add metric details view (with included tests)

---

src/pages/assessments/components/tests/TestAutoHttpsCheckForm.tsx

Fix https check message to be green if test succeeds and red if test fails

CAT-742 Update auto-https-check test message text styling

---

src/api/services/registry.ts
src/pages/metrics/Metrics.tsx

Align ui with backend changes.
Fixed sorted by by new value `metric.MTR` (the actual field is "metric_mtr" in json). In any case this allows us to sort by MTR column by default.

CAT-788 Update metric table sort by value

---

cypress.config.ts
cypress/e2e/admin.cy.ts
cypress/e2e/assess.cy.ts
cypress/e2e/assessment.cy.ts
cypress/e2e/profile.cy.ts
cypress/e2e/subject.cy.ts
cypress/e2e/validation.cy.ts
cypress/fixtures/subjects/subjects.json
cypress/fixtures/validations/validation.json
cypress/support/commands.ts
package-lock.json
package.json
src/config.json
src/pages/Profile.tsx
src/pages/assessments/AssessmentsList.tsx
vite.config.ts

This PR Updates all cypress tests and some fixtures. It also fixes the localhost/127.0.0.1 issue I was having on mac. The fix to the config for the localhost issue might introduce issues on linux like we had last time. If they do feel free to revert them to a state working for linux. The best option might be to replace it with an env variable, so that it can be altered depending on the dev's setup.
- Updated all tests back to a working state.
- Updated fixtures where needed.
- Added back some ids that were missing.
- Fixed configuration issue with localhost/127.0.0.1 for my local setup. 
- Setup and run both the fc4e-cat-ui and fc4e-cat-api locally.
- run `npx cypress open` in the fc4e-cat-ui project.
- Select E2E testing.
- Select a browser and click 'start testing'.
- This should open …

Cypress fixes

---

src/pages/admin/AdminAssessments.tsx

Trim user_id field when its long (over 15chars) and have a tooltip that displays the full id

CAT-813 Trim user_id in admin assessments table
